baseURL = 'https://ZhaoZY369.github.io/my-secret-blog/'
languageCode = 'en-us'
title = 'My Secret Blog'
theme = "PaperMod"
publishDir = "public"

# 告诉 Hugo robots.txt 是合法的输出格式
[outputFormats.RobotsTXT]
mediaType = "text/plain"
baseName = "robots"
isPlainText = true
notAlternative = true

[outputs]
home = ["HTML", "RSS", "RobotsTXT"]

[params]
  ShowReadingTime = true
  ShowToc = true
  hideSummary = true
  defaultTheme = "dark"

[privacy]
  [privacy.googleAnalytics]
    disable = true
  [privacy.disqus]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
