baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowToc = true
  hideSummary = true
  defaultTheme = "dark"

[privacy]
  [privacy.googleAnalytics]
    disable = true
  [privacy.disqus]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
